def main():
    strGreeting = getGreeting()
    greetingPayout(strGreeting.lower().strip())


def getGreeting():
    return input("Greeting of: ")


def greetingPayout(strGreeting):
    if strGreeting.startswith("hello"):
        print("$0")
    elif strGreeting.startswith("h"):
        print("$20")
    else:
        print("$100")


main()

# check50 cs50/problems/2022/python/bank

#Results for cs50/problems/2022/python/bank generated by check50 v3.3.8
#:) bank.py exists
#:) input of "Hello" yields output of $0
#:) input of " Hello " yields output of $0
#:) input of "Hello, Newman" yields output of $0
#:) input of "How you doing?" yields output of $20
#:) input of "What's happening?" yields output of $100
#:) input of "What's up?" yields output of $100