#include "helpers.h"
#include <stdio.h>

/*
BYTE  rgbtBlue;
BYTE  rgbtGreen;
BYTE  rgbtRed;
*/
// ./colorize smiley.bmp outfile.bmp
void colorize(int height, int width, RGBTRIPLE image[height][width])
{
    // Change all black pixels to a color of your choosing

    RGBTRIPLE myColour;
    myColour.rgbtBlue = 0xff;
    myColour.rgbtGreen = 0x10;
    myColour.rgbtRed = 0x00;

    for (int r = 0; r < height; r++)
    {
        for (int c = 0; c < width; c++)
        {
            if (image[r][c].rgbtBlue == 0 && image[r][c].rgbtGreen == 0 && image[r][c].rgbtRed == 0)
            {
                image[r][c] = myColour;
            }
            // printf("%i ", image[r][c].rgbtBlue);
        }
        // printf("\n");
    }
}
/*
How do you think you represent a black pixel when using a 24-bit color BMP file?    0, 0, 0
Is this the same or different when mixing paints to repesent various colors?    Opposite of mixing paint.
*/

/*
Your program should behave per the examples below.

smiley/ $ ./colorize smiley.bmp smiley_out.bmp
When your program is working correctly, you should see a new file, smiley_out.bmp in your smiley directory.
Open it up and see if the black pixels are now the color you’ve specified.

You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/smiley
Results for cs50/labs/2023/x/smiley generated by check50 v3.3.8
:) helpers.c exists
:) colorize compiles
:) colorize creates an image
:) colorize changes image colors
---
To evaluate that the style of your code (indentations and spacing) is correct, type in the following at the $ prompt.

style50 helpers.c
*/