def main():
    dict_menu = {
        "Baja Taco": 4.00,
        "Burrito": 7.50,
        "Bowl": 8.50,
        "Nachos": 11.00,
        "Quesadilla": 8.50,
        "Super Burrito": 8.50,
        "Super Quesadilla": 9.50,
        "Taco": 3.00,
        "Tortilla Salad": 8.00
    }

    total = 0.0

    while True:

        try:
            order_item = input("Item: ").title()
        except EOFError: # catch user control+d in terminal
            print() # new line after
            break

        if order_item in dict_menu:
            total += dict_menu[order_item]
        # else:
        #    print("Item does not exist.")

        print(f"Total: ${total:.2f}")


main()

# check50 cs50/problems/2022/python/taqueria
# Results for cs50/problems/2022/python/taqueria generated by check50 v3.3.8
# :) taqueria.py exists
# :) input of EOF halts program
# :) input of "taco", "taco", and "tortilla salad" results in $14.00
# :) input of "burrito", "bowl", and "nachos" results in $27.00
# :) input of "Baja Taco", "Quesadilla", and "Super Burrito" results in $21.00
# :) input of "Super quesadilla" results in $9.50
# :) input of "burger" results in reprompt