#include <cs50.h>
#include <ctype.h>
#include <stdio.h>

float calc_hours(int hours[], int weeks, char output);

int main(void)
{
    int weeks = get_int("Number of weeks taking CS50: ");
    int hours[weeks];

    for (int i = 0; i < weeks; i++)
    {
        hours[i] = get_int("Week %i HW Hours: ", i);
    }

    char output;
    do
    {
        output = toupper(get_char("Enter T for total hours, A for average hours per week: "));
    }
    while (output != 'T' && output != 'A');

    printf("%.1f hours\n", calc_hours(hours, weeks, output));
}

// TODO: complete the calc_hours function
float calc_hours(int hours[], int weeks, char output)
{
    int iTotal = 0;

    for (int i = 0; i < weeks; i++)
    {
        iTotal += hours[i];
    }

    if (output == 'A')
    {
        return ((float) iTotal) / ((float) weeks);
    }
    else
    {
        return (float) iTotal;
    }
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/hours

Results for cs50/labs/2023/x/hours generated by check50 v3.3.8
:) hours.c exists
:) hours.c compiles
:) hours sums hours over 3 weeks.
:) hours sums hours over 5 weeks.
:) hours averages hours over 3 weeks.
:) hours averages hours over 4 weeks.

---
To evaluate that the style of your code, type in the following at the $ prompt.

style50 hours.c
*/