#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[])
{
    // Check for command line args
    if (argc != 2)
    {
        printf("Usage: ./read infile\n");
        return 1;
    }

    // Create buffer to read into
    char buffer[7]; // Each plate is 6 chars long. Last index is for '\0'
    // printf("%p\n", buffer); // address of first index
    // printf("%p\n", &buffer); // address of buffer
    // printf("%c\n", *buffer); // value at first index

    // Create array to store plate numbers
    char *plates[8]; // 8 seperate plates

    FILE *infile = fopen(argv[1], "r");
    if (infile == NULL)
    {
        printf("Cannot open input file.\n");
        return 1;
    }

    int idx = 0;

    while (fread(buffer, 1, 7, infile) == 7)
    {
        // malloc
        char *plateCopy = malloc(sizeof(buffer));
        if (plateCopy == NULL)
        {
            printf("Could not allocate memory.\n");
            return 1;
        }

        // Replace '\n' with '\0'
        buffer[6] = '\0';

        // Save plate number in array
        // plates[idx] = buffer; // cannot use this, it is just storing the address that 'buffer' is pointing at.

        // Need to create memery to store the 'buffer' value elsewhere, since 'buffer' will be reused and the previous value
        // is overwritten. Then for each char *plate can point to the new memory locations
        strcpy(plateCopy, buffer); // copy value from 'buffer' to new mem location
        plates[idx] = plateCopy;   // assign plates[idx] char * to mem address 'plateCopy' has.
        idx++;
    }
    // printf("mem of plates array start, %p\n", plates);
    // printf("mem of plates array start, %p\n", &plates);
    for (int i = 0; i < 8; i++)
    {
        // printf("===========\n");
        // printf("mem of where plates[i] is pointing, %p\n", &plates[i]);
        printf("%s\n", plates[i]);
        free(plates[i]);
    }

    fclose(infile);
}

/*
valgrind ./license plates.txt

Your program should behave per the examples below.

license/ $ ./license plates.txt
11ZT00
1KAD21
78ZZ01
99ZZ11
72ZZ21
98ZZ31
44ZW41
34ZZ51
You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/license

Results for cs50/labs/2023/x/license generated by check50 v3.3.8
:) license.c exists
:) license.c compiles
:) license prints all plates.
---
To evaluate that the style of your code, type in the following at the $ prompt.

style50 license.c
*/