#include <cs50.h>
#include <math.h>
#include <stdio.h>

bool prime(int number);

int main(void)
{
    int min;
    do
    {
        min = get_int("Minimum: ");
    }
    while (min < 1);

    int max;
    do
    {
        max = get_int("Maximum: ");
    }
    while (min >= max);

    for (int i = min; i <= max; i++)
    {
        if (prime(i))
        {
            printf("%i\n", i);
        }
    }
}

bool prime(int number)
{
    // TODO
    int iHalf = floor(sqrt(number));
    if (number == 1)
    {
        return false;
    }

    for (int i = 2; i <= iHalf; i++)
    {
        if (number % i == 0)
        {
            return false;
        }
    }
    return true;
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit, by typing in the
following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/prime
Green smilies mean your program has passed a test! Red frownies will indicate your program output something unexpected.
Visit the URL that check50 outputs to see the input check50 handed to your program, what output it expected, and what output
your program actually gave.

Results for cs50/labs/2023/x/prime generated by check50 v3.3.8
:) prime.c exists
:) prime.c compiles
:) Input of 1 and 10 yields all prime numbers between 1 and 10, inclusive
:) Input of 10 and 25 yields all prime numbers between 10 and 25, inclusive
:) Input of 50 and 60 yields all prime numbers between 50 and 60, inclusive
----
To evaluate that the style of your code (indentations and spacing) is correct, type in the following at the $ prompt.

style50 prime.c
*/