// Write a function to replace vowels with numbers
// Get practice with strings
// Get practice with command line
// Get practice with switch

#include <cs50.h>
#include <stdio.h>
#include <string.h>

string replace(string sInput);

int main(int argc, string argv[])
{
    if (argc != 2)
    {
        printf("This program only accepts one command-line argument!\n");
        return 1;
    }

    printf("%s\n", replace(argv[1]));
}

// This function will change the following vowels to numbers:
// a becomes 6, e becomes 3, i becomes 1, o becomes 0 and u does not change.
string replace(string sInput)
{
    int iLen = strlen(sInput);
    for (int i = 0; i < iLen; i++)
    {
        switch (sInput[i])
        {
            case 'a':
                sInput[i] = '6';
                break;

            case 'e':
                sInput[i] = '3';
                break;

            case 'i':
                sInput[i] = '1';
                break;

            case 'o':
                sInput[i] = '0';
                break;

            default:
                break;
        }
    }

    return sInput;
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/no-vowels

Results for cs50/labs/2023/x/no-vowels generated by check50 v3.3.8
:) no-vowels.c exists
:) no-vowels.c compiles
:) Input of "hello" produces output "h3ll0"
:) Input of "pseudocode" produces output "ps3ud0c0d3"
:) Input of "Hello World" produces output "H3ll0 W0rld"
:) Input of "This is CS50" produces output "Th1s 1s CS50"
---

Green smilies mean your program has passed a test! Red frownies will indicate your program output something unexpected.
Visit the URL that check50 outputs to see the input check50 handed to your program, what output it expected, and what output your
program actually gave.

To evaluate that the style of your code (indentations and spacing) is correct, type in the following at the $ prompt.

style50 no-vowels.c
*/