// Check that a password has at least one lowercase letter, uppercase letter, number and symbol
// Practice iterating through a string
// Practice using the ctype library

#include <cs50.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>

bool valid(string password);

int main(void)
{
    string password = get_string("Enter your password: ");
    if (valid(password))
    {
        printf("Your password is valid!\n");
    }
    else
    {
        printf("Your password needs at least one uppercase letter, lowercase letter, number and symbol\n");
    }
}

// TODO: Complete the Boolean function below
bool valid(string password)
{
    bool lowerCaseFlag, upperCaseFlag, numberFlag, symbolFlag = false;
    int iLen = strlen(password);
    for (int i = 0; i < iLen; i++)
    {

        if (islower(password[i]))
        {
            lowerCaseFlag = true;
        }
        else if (isupper(password[i]))
        {
            upperCaseFlag = true;
        }
        else if (isdigit(password[i]))
        {
            numberFlag = true;
        }
        else if (ispunct(password[i]))
        {
            symbolFlag = true;
        }

        if (lowerCaseFlag == true && upperCaseFlag == true && numberFlag == true && symbolFlag == true)
        {
            return true;
        }
    }

    return false;
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/password

Results for cs50/labs/2023/x/password generated by check50 v3.3.8
:) password.c exists
:) password.c compiles
:) Password of 3PQvbQ6_GvneW!3R is accepted.
:) Password of hqsk3wb. is rejected for lack of uppercase characters.
:) Password of F-WH8PQP is rejected for lack of lowercase characters.
:) Password of VnrHMtV4 is rejected for lack of symbols.
:) Password of iWnktW*q is rejected for lack of numbers.
---
To evaluate that the style of your code, type in the following at the $ prompt.

style50 password.c
*/