// Calculate your half of a restaurant bill
// Data types, operations, type casting, return value

#include <cs50.h>
#include <stdio.h>

float half(float bill, float tax, int tip);

int main(void)
{
    float bill_amount = get_float("Bill before tax and tip: ");
    float tax_percent = get_float("Sale Tax Percent: ");
    int tip_percent = get_int("Tip percent: ");

    printf("You will owe $%.2f each!\n", half(bill_amount, tax_percent, tip_percent));
}

// TODO: Complete the function
float half(float bill, float tax, int tip)
{
    return ((bill * (1 + (tax / 100))) * ((1 + ((float) tip / 100)))) / 2;
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit,
by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/half
Green smilies mean your program has passed a test! Red frownies will indicate your program output something unexpected.
Visit the URL that check50 outputs to see the input check50 handed to your program, what output it expected, and what output your
program actually gave.

Results for cs50/labs/2023/x/half generated by check50 v3.3.8
:) half.c exists
:) half.c compiles
:) Bill of $50, with 10% tax and 20% tip, creates output of $33.00
:) Bill of $50, with 12.5% tax and 20% tip, creates output of $33.75
:) Bill of $100, with 12.5% tax and 15% tip, creates output of $64.69
:) Bill of $96.40, with 13% tax and 14% tip, creates output of $62.09

--
To evaluate that the style of your code (indentations and spacing) is correct, type in the following at the $ prompt.

style50 half.c
*/