// Simulate genetic inheritance of blood type

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Each person has two parents and two alleles
typedef struct person
{
    struct person *parents[2];
    char alleles[2];
} person;

const int GENERATIONS = 3;
const int INDENT_LENGTH = 4;

person *create_family(int generations);
void print_family(person *p, int generation);
void free_family(person *p);
char random_allele();

// ./inheritance
// valgrind ./inheritance
int main(void)
{
    // Seed random number generator
    srand(time(0));

    // Create a new family with three generations
    person *p = create_family(GENERATIONS);
    if (NULL)
    {
        return 1;
    }

    // Print family tree of blood types
    print_family(p, 0);

    // Free memory
    free_family(p);
}

// Create a new individual with `generations`
person *create_family(int generations)
{
    // TODO: Allocate memory for new person
    person *per = malloc(sizeof(person));
    if (per == NULL)
    {
        // would need to free previous nodes. In this lab, do not need to.
        return NULL;
    }

    // If there are still generations left to create
    if (generations > 1)
    {
        // Create two new parents for current person by recursively calling create_family
        person *parent0 = create_family(generations - 1);
        person *parent1 = create_family(generations - 1);

        // TODO: Set parent pointers for current person
        per->parents[0] = parent0;
        per->parents[1] = parent1;

        // TODO: Randomly assign current person's alleles based on the alleles of their parents
        per->alleles[0] = parent0->alleles[(rand() % 2)];
        per->alleles[1] = parent1->alleles[(rand() % 2)];
    }

    // If there are no generations left to create
    else
    {
        // TODO: Set parent pointers to NULL
        per->parents[0] = NULL;
        per->parents[1] = NULL;

        // TODO: Randomly assign alleles
        per->alleles[0] = random_allele();
        per->alleles[1] = random_allele();
    }

    // TODO: Return newly created person
    return per;
}

// Free `p` and all ancestors of `p`.
void free_family(person *p)
{
    // TODO: Handle base case
    if (p == NULL)
    {
        return;
    }
    // TODO: Free parents recursively
    else
    {
        free_family(p->parents[0]);
        free_family(p->parents[1]);
    }
    // TODO: Free child
    free(p);

}

// Print each family member and their alleles.
void print_family(person *p, int generation)
{
    // Handle base case
    if (p == NULL)
    {
        return;
    }

    // Print indentation
    for (int i = 0; i < generation * INDENT_LENGTH; i++)
    {
        printf(" ");
    }

    // Print person
    if (generation == 0)
    {
        printf("Child (Generation %i): blood type %c%c\n", generation, p->alleles[0], p->alleles[1]);
    }
    else if (generation == 1)
    {
        printf("Parent (Generation %i): blood type %c%c\n", generation, p->alleles[0], p->alleles[1]);
    }
    else
    {
        for (int i = 0; i < generation - 2; i++)
        {
            printf("Great-");
        }
        printf("Grandparent (Generation %i): blood type %c%c\n", generation, p->alleles[0], p->alleles[1]);
    }

    // Print parents of current generation
    print_family(p->parents[0], generation + 1);
    print_family(p->parents[1], generation + 1);
}

// Randomly chooses a blood type allele.
char random_allele()
{
    int r = rand() % 3;
    if (r == 0)
    {
        return 'A';
    }
    else if (r == 1)
    {
        return 'B';
    }
    else
    {
        return 'O';
    }
}

/*
Execute the below to evaluate the correctness of your code using check50. But be sure to compile and test it yourself as well!

check50 cs50/labs/2023/x/inheritance

Results for cs50/labs/2023/x/inheritance generated by check50 v3.3.8
:) inheritance.c exists
:) inheritance compiles
:) create_family creates correct size of family
:) create_family follows inheritance rules 1
:) create_family follows inheritance rules 2
:) create_family follows inheritance rules 3
:) free_family results in no memory leakages
---
Execute the below to evaluate the style of your code using style50.

style50 inheritance.c
*/