# from sys import argv    # for command line inputs
# from sys import exit
import sys
from pyfiglet import Figlet
import random

def main():
    optionList = ["-f", "--font"]
    lenOfArgv = len(sys.argv)
    randNum = 0;
    font = ""

    if (lenOfArgv != 1 and lenOfArgv != 3) or (lenOfArgv == 3 and sys.argv[1] not in optionList):
        print("Invalid usage")
        sys.exit(1)

    figlet = Figlet()
    listOfFonts = figlet.getFonts() # get a list of all available fonts

    if(lenOfArgv == 3 and sys.argv[1] in optionList):
        if sys.argv[2] not in listOfFonts:
            print("Invalid usage")
            sys.exit(1)

        font = sys.argv[2]
    else:
        font = random.choice(listOfFonts)  # if not arguments, randomize font

    figlet.setFont(font = font)

    inText = input("Input: ")

    # print(f"font is : {font}")
    print("Output:")
    print(figlet.renderText(inText))

    sys.exit(0)


main()
# check50 cs50/problems/2022/python/figlet

#Results for cs50/problems/2022/python/figlet generated by check50 v3.3.8
#:) figlet.py exists
#:) figlet.py exits given one command-line argument
#:) figlet.py exits given invalid first command-line argument
#:) figlet.py exits given invalid second command-line argument
#:) figlet.py renders slanted text
#:) figlet.py renders rectangular text
#:) figlet.py renders alphabet text