// Practice writing a function to find a max value

#include <cs50.h>
#include <stdio.h>

int max(int array[], int n);

int main(void)
{
    int n;
    do
    {
        n = get_int("Number of elements: ");
    }
    while (n < 1);

    int arr[n];

    for (int i = 0; i < n; i++)
    {
        arr[i] = get_int("Element %i: ", i);
    }

    printf("The max value is %i.\n", max(arr, n)); // passing the reference to the first elem, n = size of array
}

// TODO: return the max value
int max(int array[], int n)
{
    int max;
    if (n > 0)
    {
        max = array[0];
    }

    for (int i = 0; i < n; i++)
    {
        if (array[i] > max)
        {
            max = array[i];
        }
    }
    return max;
}

/*
You can check your code using check50, a program that CS50 will use to test your code when you submit,
    by typing in the following at the $ prompt. But be sure to test it yourself as well!

check50 cs50/labs/2023/x/max

Results for cs50/labs/2023/x/max generated by check50 v3.3.8
:) max.c exists
:) max.c compiles
:) Returns 3 from 0, 1, 3
:) Returns 4 from -10, 4, 2
:) Returns -10 from -10, -50, -100
----
To evaluate that the style of your code, type in the following at the $ prompt.

style50 max.c
*/