# TODO

while True:
    try:
        height = int(input("Height: "))
    except ValueError:
        # print("Not an int.")
        continue

    if(1 <= height <=8):
        break;

for i in range(1, height + 1):
    spaces = height - i
    print((" " * spaces) + ("#" * i) + "  " + ("#" * i))


#Results for cs50/problems/2023/x/sentimental/mario/more generated by check50 v3.3.8
#:) mario.py exists.
#:) rejects a height of -1
#:) rejects a height of 0
#:) handles a height of 1 correctly
#:) handles a height of 2 correctly
#:) handles a height of 8 correctly
#:) rejects a height of 9, and then accepts a height of 2
#:) rejects a non-numeric height of "foo"
#:) rejects a non-numeric height of ""