#include <cs50.h>
#include <stdio.h>

#define POUNDSYMBOL '#'
#define SPACESYMBOL ' '
#define GAPSIZE 2
#define PYRAMIDLOWERBOUND 1
#define PYRAMIDUPPERBOUND 8

int getHeight(void);
void printSymbols(int iNum, char cSymbol);
void printPyramids(int iHeight);

int main(void)
{
    // prompt user for height of the pyramids
    int iHeight = getHeight();

    // print the pyraminds based on the user's specified height
    printPyramids(iHeight);
}

/*
Prompt user for an int for the height of the pyramids. Must be [1,8]
Params: N/a
Return: int, the height of the pyraminds.
*/
int getHeight(void)
{

    int n = 0;
    do
    {
        n = get_int("Height: ");
    }
    while (n < PYRAMIDLOWERBOUND || n > PYRAMIDUPPERBOUND);

    return n;
}

/*
Output the terminal art to represent the Mario pyramids with the specified height. The gap between the 2 pyramids is 2 * width of a `#` sybmol, which is just a `space` char.
Params:
    int iHeight: the specified height of the pyramids
Return: void
*/
void printPyramids(int iHeight)
{
    int iNumOfSpace = 0;
    int iNumOfPound = 0;
    // 0 is the top level
    for (int i = 0; i < iHeight; i++)
    {
        iNumOfSpace =
            iHeight - 1 - i; // -1 due to starting at 0. E.x. of iHeight = 4, on top level, therefore iNumOfSpace = 4-1-0 = 3.
        iNumOfPound = iHeight - iNumOfSpace; // The remainder of the row is the `#` sybmol. E.x. iNumOfPound = 4-3=1.

        // left side
        printSymbols(iNumOfSpace, SPACESYMBOL);
        printSymbols(iNumOfPound, POUNDSYMBOL);

        // gap
        printSymbols(GAPSIZE, SPACESYMBOL);

        // right side
        printSymbols(iNumOfPound, POUNDSYMBOL);
        // printSymbols(iNumOfSpace, SPACESYMBOL); // don't need this, just go to new line.

        printf("\n");
    }
}

// Print sybmol `cSymbol` `iNum` number of times.
void printSymbols(int iNum, char cSymbol)
{
    for (int i = 0; i < iNum; i++)
    {
        printf("%c", cSymbol);
    }
}

/*
Test functions:
    int getHeight(void)
        Ranges: (-inf, 1), [1,8], (8, inf)

        Test cases:
            -1  ;Expected Res: reprompt
            1   ;Expected Res: print correct pyramid
            8   ;Expected Res: print correct pyramid
            9   ;Expected Res: reprompt

            H   ;Expected Res: reprompt
            [enter] ;Expected Res: reprompt


Does your code work as prescribed when you input

-1 (or other negative numbers)?
0?
1 through 8?
9 or other positive numbers?
letters or words?
no input at all, when you only hit Enter?
You can also execute the below to evaluate the correctness of your code using check50. But be sure to compile and test it yourself
as well!

check50 cs50/problems/2023/x/mario/more


Results for cs50/problems/2023/x/mario/more generated by check50 v3.3.8
:) mario.c exists
:) mario.c compiles
:) rejects a height of -1
:) rejects a height of 0
:) handles a height of 1 correctly
:) handles a height of 2 correctly
:) handles a height of 8 correctly
:) rejects a height of -1, and then accepts a height of 2
:) rejects a non-numeric height of "foo"
:) rejects a non-numeric height of ""
----


Execute the below to evaluate the style of your code using style50.

style50 mario.c
*/